
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: taleemAdmin
      MONGO_INITDB_ROOT_PASSWORD: bils32611246950
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://taleemAdmin:bils32611246950@mongo:27017/taleemDB?authSource=admin
      - JWT_SECRET=supersecret123
      - ADMIN_SECRET=workshop-super-secret

volumes:
  mongo-data:
